const shopActionType={
    UPDATE_COLLECTION:'UPDATE_COLLECTION',
    FETCH_COLLECTION_START:' FETCH_COLLECTION_START',
    FETCH_COLLECTION_SUCCSESS:'FETCH_COLLECTION_SUCCSESS',
    FEATCH_COLLECTION_FAILUR:'FEATCH_COLLECTION_FAILUR'
}
export default shopActionType